<?php

/**
 * @file
 * Main file for Notification Plugin module.
 */

/**
 * Implements hook_user_login().
 */
function notification_plugin_user_login($account) {

  // Get notification manager from service container.
  $plugin_manager = \Drupal::service('plugin.manager.notification_plugin');

  // Get notification type plugin definitions.
  $plugins = $plugin_manager->getDefinitions();

  // Loop through plugin definitions.
  foreach ($plugins as $notification) {

    // Create instance of the current plugin.
    $instance = $plugin_manager->createInstance($notification['id']);

    // Set message with the message from the plugin.
    drupal_set_message($instance->getNotification());
  }
}
